#CI项目
name: WRT-TEST

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      CONFIG:
        default: 'MTK-7981'
        required: true
        type: choice
        options: [MT7981, MT7986, TEST]
      SOURCE:
        default: 'NekokeCore/immortalwrt-mt798x-24.10'
        required: true
        type: choice
        options: [hanwckf/immortalwrt-mt798x, padavanonly/immortalwrt-mt798x, padavanonly/immortalwrt-mt798x-23.05, NekokeCore/immortalwrt-mt798x-24.10]
      BRANCH:
        default: 'openwrt-24.10'
        required: true
        type: string
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'true'
        required: true
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    name: ${{inputs.CONFIG}}
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{inputs.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: CWRT
      #默认WIFI名称
      WRT_SSID: CWRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{inputs.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{inputs.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{inputs.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
