#CI项目名
name: WRT-TEST

on:
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: MTK-7986
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: CWRT
      #默认WIFI名
      WRT_WIFI: ImmortalWrt
      #默认密码，仅作展示，请勿乱改
      WRT_PW: 无
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/hanwckf/immortalwrt-mt798x.git
      #默认分支
      WRT_BRANCH: openwrt-21.02
      #仅输出配置文件，非必选参数
      WRT_CFG: true
      #内存压缩，可选参数，默认关闭，256内存推荐开启
      #WRT_SHRINK: true
